<?php


namespace App\Models;


class AmoCompany extends AmoCustomFieldsKeys
{
    /**
     * id соответствующих полей в АМО
     */
    const ID_COMP = 'ID_COMP';
    const ID_COMP_FIELD_TYPE_ID = 'ID_COMP_FIELD_TYPE_ID';
    const COMPNAME = 'COMPNAME';
    const COMPNAME_FIELD_TYPE_ID = 'COMPNAME_FIELD_TYPE_ID';
    const COMPFULLNAME = 'COMPFULLNAME';
    const COMPFULLNAME_FIELD_TYPE_ID = 'COMPFULLNAME_FIELD_TYPE_ID';
    const MAINCOMPNAME = 'MAINCOMPNAME';
    const MAINCOMPNAME_FIELD_TYPE_ID = 'MAINCOMPNAME_FIELD_TYPE_ID';
    const INN = 'INN';
    const INN_FIELD_TYPE_ID = 'INN_FIELD_TYPE_ID';
    const KPP = 'KPP';
    const KPP_FIELD_TYPE_ID = 'KPP_FIELD_TYPE_ID';
    const MANAGER = 'MANAGER';
    const MANAGER_FIELD_TYPE_ID = 'MANAGER_FIELD_TYPE_ID';
    const ADDRESS = 'ADDRESS';
    const ADDRESS_FIELD_TYPE_ID = 'ADDRESS_FIELD_TYPE_ID';
    const MAINADDRESS = 'MAINADDRESS';
    const MAINADDRESS_FIELD_TYPE_ID = 'MAINADDRESS_FIELD_TYPE_ID';
    const DELIVERY = 'DELIVERY';
    const DELIVERY_FIELD_TYPE_ID = 'DELIVERY_FIELD_TYPE_ID';
    const EMAIL = 'EMAIL';
    const EMAIL_FIELD_TYPE_ID = 'EMAIL_FIELD_TYPE_ID';
    const TEL = 'TEL';
    const TEL_FIELD_TYPE_ID = 'TEL_FIELD_TYPE_ID';
    const ACCOUNT = 'ACCOUNT';
    const ACCOUNT_FIELD_TYPE_ID = 'ACCOUNT_FIELD_TYPE_ID';
    const BANK = 'BANK';
    const BANK_FIELD_TYPE_ID = 'BANK_FIELD_TYPE_ID';
    const ACTIVITY = 'ACTIVITY';
    const ACTIVITY_FIELD_TYPE_ID = 'ACTIVITY_FIELD_TYPE_ID';
    const DELIVERY_TIME_FROM = 'DELIVERY_TIME_FROM';
    const DELIVERY_TIME_FROM_FIELD_TYPE_ID = 'DELIVERY_TIME_FROM_FIELD_TYPE_ID';
    const DELIVERY_TIME_TO = 'DELIVERY_TIME_TO';
    const DELIVERY_TIME_TO_FIELD_TYPE_ID = 'DELIVERY_TIME_TO_FIELD_TYPE_ID';
    const ADDINFO = 'ADDINFO';
    const ADDINFO_FIELD_TYPE_ID = 'ADDINFO_FIELD_TYPE_ID';
    const ROLE = 'ROLE';
    const ROLE_ENUM_CLIENT = 'ROLE_ENUM_CLIENT';
    const ROLE_FIELD_TYPE_ID = 'ROLE_FIELD_TYPE_ID';
    const COMPROLE = 'COMPROLE';
    const COMPROLE_PHYSICAL = 'COMPROLE_PHYSICAL';
    const COMPROLE_LEGAL = 'COMPROLE_LEGAL';
    const COMPROLE_FIELD_TYPE_ID = 'COMPROLE_FIELD_TYPE_ID';
    const UPD = 'UPD';
    const UPD_FIELD_TYPE_ID = 'UPD_FIELD_TYPE_ID';
    const ACCESS_GROUP = 'ACCESS_GROUP';
    const ACCESS_GROUP_FIELD_TYPE_ID = 'ACCESS_GROUP_FIELD_TYPE_ID';
    const KOORDLONG = 'KOORDLONG';
    const KOORDLONG_FIELD_TYPE_ID = 'KOORDLONG_FIELD_TYPE_ID';
    const KOORDLATI = 'KOORDLATI';
    const KOORDLATI_FIELD_TYPE_ID = 'KOORDLATI_FIELD_TYPE_ID';
    const SYNCHRO_WITH_1C = 'SYNCHRO_WITH_1C';
    const SYNCHRO_WITH_1C_FIELD_TYPE_ID = 'SYNCHRO_WITH_1C_FIELD_TYPE_ID';
    const APPROVED_BY_LEGAL = 'APPROVED_BY_LEGAL';
    const APPROVED_BY_LEGAL_FIELD_TYPE_ID = 'APPROVED_BY_LEGAL_FIELD_TYPE_ID';
    const LEGAL_APPROVAL_SEND = 'LEGAL_APPROVAL_SEND';
    const LEGAL_APPROVAL_SEND_FIELD_TYPE_ID = 'LEGAL_APPROVAL_SEND_FIELD_TYPE_ID';
    const SHIPMENT_DISALLOW_FROM = 'SHIPMENT_DISALLOW_FROM';
    const SHIPMENT_DISALLOW_FROM_FIELD_TYPE_ID = 'SHIPMENT_DISALLOW_FROM_FIELD_TYPE_ID';
    const SHIPMENT_DISALLOW = 'SHIPMENT_DISALLOW';
    const SHIPMENT_DISALLOW_FIELD_TYPE_ID = 'SHIPMENT_DISALLOW_FIELD_TYPE_ID';

}
