<?php


namespace App\Models;


class AmoLead extends AmoCustomFieldsKeys
{
    const PRICE_CUSTOM_FIELD = 'PRICE_CUSTOM_FIELD';
    const PRICE_CUSTOM_FIELD_FIELD_TYPE_ID = 'PRICE_CUSTOM_FIELD_FIELD_TYPE_ID';

    // order tab
    const ORDER_GUID = 'ORDER_GUID';
    const ORDER_GUID_FIELD_TYPE_ID = 'ORDER_GUID_FIELD_TYPE_ID';
    const ORDER_NUMBER = 'ORDER_NUMBER';
    const ORDER_NUMBER_FIELD_TYPE_ID = 'ORDER_NUMBER_FIELD_TYPE_ID';
    const REALIZATION_GUID = 'REALIZATION_GUID';
    const REALIZATION_GUID_FIELD_TYPE_ID = 'REALIZATION_GUID_FIELD_TYPE_ID';
    const REALIZATION_NUMBER = 'REALIZATION_NUMBER';
    const REALIZATION_NUMBER_FIELD_TYPE_ID = 'REALIZATION_NUMBER_FIELD_TYPE_ID';

    // payment tab
    const PAYMENT_BUDGET = 'PAYMENT_BUDGET';
    const PAYMENT_BUDGET_FIELD_TYPE_ID = 'PAYMENT_BUDGET_FIELD_TYPE_ID';
    const PAYMENT_STATUS = 'PAYMENT_STATUS';
    const PAYMENT_STATUS_FIELD_TYPE_ID = 'PAYMENT_STATUS_FIELD_TYPE_ID';
    const PAYMENT_STATUS_ENUM_PAID = 'PAYMENT_STATUS_ENUM_PAID';
    const PAYMENT_STATUS_ENUM_NOT_PAID = 'PAYMENT_STATUS_ENUM_NOT_PAID';
    const PAYMENT_STATUS_ENUM_PARTIAL_PAID = 'PAYMENT_STATUS_ENUM_PARTIAL_PAID';
    const PAYMENT_AMOUNT = 'PAYMENT_AMOUNT';
    const PAYMENT_AMOUNT_FIELD_TYPE_ID = 'PAYMENT_AMOUNT_FIELD_TYPE_ID';

    // courier tab
    const COURIER_SURNAME = 'COURIER_SURNAME';
    const COURIER_SURNAME_FIELD_TYPE_ID = 'COURIER_SURNAME_FIELD_TYPE_ID';
    const COURIER_NAME = 'COURIER_NAME';
    const COURIER_NAME_FIELD_TYPE_ID = 'COURIER_NAME_FIELD_TYPE_ID';
    const COURIER_OTCHESTVO = 'COURIER_OTCHESTVO';
    const COURIER_OTCHESTVO_FIELD_TYPE_ID = 'COURIER_OTCHESTVO_FIELD_TYPE_ID';
    const COURIER_PHONE = 'COURIER_PHONE';
    const COURIER_PHONE_FIELD_TYPE_ID = 'COURIER_PHONE_FIELD_TYPE_ID';
    const COURIER_ARRIVAL_PLAN = 'COURIER_ARRIVAL_PLAN';
    const COURIER_ARRIVAL_PLAN_FIELD_TYPE_ID = 'COURIER_ARRIVAL_PLAN_FIELD_TYPE_ID';
    const COURIER_ARRIVAL_FACT = 'COURIER_ARRIVAL_FACT';
    const COURIER_ARRIVAL_FACT_FIELD_TYPE_ID = 'COURIER_ARRIVAL_FACT_FIELD_TYPE_ID';
    const COURIER_DEPARTURE_PLAN = 'COURIER_DEPARTURE_PLAN';
    const COURIER_DEPARTURE_PLAN_FIELD_TYPE_ID = 'COURIER_DEPARTURE_PLAN_FIELD_TYPE_ID';
    const COURIER_DEPARTURE_FACT = 'COURIER_DEPARTURE_FACT';
    const COURIER_DEPARTURE_FACT_FIELD_TYPE_ID = 'COURIER_DEPARTURE_FACT_FIELD_TYPE_ID';

}
